In [1]:
# importing numpy
import numpy as np

## Creating arrays in numpy

### Creating an array from a Python list

In [2]:
list1 = [10,20,30]
list1

[10, 20, 30]

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [5]:
# We can check the type of arr1, we can see it is an ndarray 
# (or n-dimensional array)
# In this case we have only created a one dimensional array so far
type(arr1)

numpy.ndarray

### Using arange() to create an array

arrange() creates an array from a range of numbers

In [8]:
arr2 = np.arange(10,20,1) # (Start, Stop, Increment)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Multi-dimensional arrays

When we combine arrays together we can add dimensions. So two arrays together makes a 2d array, this creates a matrix for use to do matrix operations

In [11]:
# Creating a new list to join to first one
list2 = [40,50,60]

# Join the lists together
list3 = [list1, list2]
list3

# Create 2-D array from the joined lists
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [12]:
# Lets find the shape of the array
arr3.shape

(2, 3)

#### Three Dimensional Arrays

In [14]:
arr3dim = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[7,8,9]]])
arr3dim

array([[[1, 2, 3],
        [4, 5, 6]],

       [[5, 6, 7],
        [7, 8, 9]]])

In [15]:
arr3dim.shape

(2, 2, 3)

### Using arrays and scalars

In [17]:
# We can perform simple multiplication to our ndarrays
# For example
arr3dim * 3

array([[[ 3,  6,  9],
        [12, 15, 18]],

       [[15, 18, 21],
        [21, 24, 27]]])

In [21]:
# How is this different to
list1 * 3

# Duplicates the list 3 times

[10, 20, 30, 10, 20, 30, 10, 20, 30]

This is where numpy comes in, arryas and lists are treated differently

We can also multiply an array by another array using a matrix operation

In [22]:
# Creating another array which has the same size as arr1
arr11 = np.array(list2)
arr11

array([40, 50, 60])

In [24]:
# What will happend here
arr1 * arr11

# Individual numbers are multiplied based on their positions in their array

array([1600, 2500, 3600])

In [25]:
# What if we tried to multiply arrays of different size/ shapes?
arr1 * arr2

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [32]:
# But it is possible to multuply arrays of different dimesions but the same element size
t = arr1 * arr3dim
t.shape

(2, 2, 3)

## Task

## Shape = (depth, rows, columns)

Create ndarrays of the following sizes:
One dimensional array with 12 elements (12,)
Two dimensional array size (3, 4)
Three dimensional array size (2, 5, 4)
Check the size of your ndarray to ensure it is correct

In [59]:
#One dimensional array with 12 elements (12,)
arr5 = np.arange(0,12,1)
arr5

# Two dimensional array size (3, 4)
list5 = [10,20,30, 10]
list6 = [40,50,60, 10]
list7 = [70,80,90, 10]
list8 = [list5,list6,list7]
arrT = np.array(list8)
arrT.shape

# Three dimensional array size (2, 5, 4)
arr5dim = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]
    ],
    [
        [21, 22, 23, 24],
        [25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36],
        [37, 38, 39, 40]
    ]
])
arr5dim.shape

28

# Accessing values in ndarrays

In [52]:
# How can we access the 60?
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [56]:
arr3[1][2]

60

In [57]:
# We can also use
arr3[1,2]

60

In [60]:
# What if we want the last numbers in each row?
arr3[:,2]

array([30, 60])

In [62]:
arr3[:,1]

array([20, 50])

# Statistical functions and arrays

There are many built in statistical functions

In [63]:
# Sum of all values
arr3.sum()

210

In [64]:
# Sum of all values column wise
arr3.sum(0)

array([50, 70, 90])

In [65]:
# Sum of all values row wise
arr3.sum(1)

array([ 60, 150])

In [66]:
# Find the mean
arr3.mean()

35.0

In [68]:
# Find the SD
arr3.std()

17.07825127659933

In [69]:
# Find the varience
arr3.var()

291.6666666666667

In [70]:
# Find the min
arr3.min()

10

In [71]:
# Find the max
arr3.max()

60

#### Iterating through ndarryas

In [77]:
# 1d array:
for x in arr1:
    print(x)

40
50
60


In [78]:
# 2d array:
for dim in arr3:
    for num in dim:
        print(num)

10
20
30
40
50
60


In [79]:
# Alternative:
for x in np.nditer(arr3):
    print(x)


10
20
30
40
50
60


#### Saving and loading in numpy

In [80]:
# To save an array as file
np.save('new', arr3)

In [81]:
# Load file
np.load('new.npy')

array([[10, 20, 30],
       [40, 50, 60]])

In [82]:
# Saving as txt
np.savetxt('new.txt', arr3, delimiter=',')

In [83]:
# Load txt
np.loadtxt('new.txt', delimiter=',')

array([[10., 20., 30.],
       [40., 50., 60.]])